<?php

/**
 * ioBasicPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ioBasicPageTable extends ioPageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ioBasicPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ioBasicPage');
    }
}