<?php

/**
 * msBlogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class msBlogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object msBlogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('msBlog');
    }
}