<?php

/**
 * msCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class msCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object msCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('msCategory');
    }
}