# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
#  param: { module: default, action: index }
  param: { module: home, action: index }

pages:
  url:   /pages/:slug
  class: sfDoctrineRoute
  param:
    module:  myPageAction
    action:  show
  options:
    model:   ioPage
    type:    object

about:
  url:   /about
  class: sfDoctrineRoute
  param:
    module:  main
    action:  about
    internal_slug:  about_us
  options:
    model:  ioPage
    type:   object
    method: fetchFromInternalSlug


# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*

error404:
  url:   /*
  param: { module: default, action: error404 }
