<?php

/**
 * ioBlogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ioBlogTable extends PluginioBlogTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ioBlogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ioBlog');
    }
}